### ISSUE TITLE
<template> multi-line comments shift with each format

### ISSUE THREAD

**Issue by jl8n** [vuejs/language-tools#2505]
Using Vue Language Features (Volar) v1.2.0 in VSCode

Before formatting:

```html
          <!--
            <div>
              <p>Hello world!</p>
            </div>
          -->
```

First format:

```html
          <!--
              <div>
                <p>Hello world!</p>
              </div>
            -->
```

Second format:

```html
          <!--
                <div>
                  <p>Hello world!</p>
                </div>
              -->
```

Third format:

```html
          <!--
                  <div>
                    <p>Hello world!</p>
                  </div>
                -->
```

and so on,

This does not happen with single line comments such as:

```html
<!-- <div><p>Hello world!</p></div> -->
```

**Comment by pierresaid** [comment]
Same as #2470 and as #2478

**Comment by johnsoncodehk** [comment]
This issue should have been fixed in 1.1.4 by #2420. Unfortunately I can't reproduce it at the moment.

**Comment by mrinc** [comment]
@johnsoncodehk  - here is a file that it is doing it too - https://gist.github.com/mrinc/84e27a1bc0fcdfa79be228c96c387286   

You can actually see the formatting.   
Vue.volar- `v1.3.12`   
Vue.vscode-typescript-vue-plugin - `v1.3.12`  

Maybe you can replicate the issue on your end with a copy of a file that is causing it.  

Originally I thought it may be caused by errors in the file, but that doesn't seem to affect it, so it's definately something else.  
From it's behavour, I believe there might be something to do with the position of the code.  
Like every time we format, it adds 2 spaces as if you'd inner indent the code.  
\- which makes sense if you were to think of a div, inner code is indented.  
So it might not be checking or validating the indent correctly - so something like that.

**Comment by mariusa** [comment]
Still happens with v1.2.0

> Like every time we format, it adds 2 spaces as if you'd inner indent the code.

Right. Only for multi-line comments in `<template>` section in .vue files (if relevant, `<script setup lang="ts">`)

Here's how it looks, initial and then after a few Ctrl+S (with auto-format on Save)

![Screenshot from 2023-04-07 14-06-29](https://user-images.githubusercontent.com/1283842/230599294-57b9f8ef-d891-4756-afa1-0d1a62a53054.png)
![Screenshot from 2023-04-07 14-06-39](https://user-images.githubusercontent.com/1283842/230599295-c57f4259-4c54-4522-86a5-83591e38b78e.png)

![Screenshot from 2023-04-07 14-06-18](https://user-images.githubusercontent.com/1283842/230599286-099e7630-c8f9-4138-bd12-487b8efa5546.png)

**Comment by johnsoncodehk** [comment]
I can reproduce with the gist, thanks.

**Comment by mariusa** [comment]
Thank you for the fix! It works
