### ISSUE TITLE
vue-tsc:1.7.12 memory heep size

### ISSUE THREAD

**Issue by adoin** [vuejs/language-tools#3281]
When I update vue-tsc to1.7.12, heep memory like #3239 , my project using vxe-table ant-design-vue.
And 1.7.11 didn't find I have idx in template, treat it as unused.

![image](https://github.com/vuejs/language-tools/assets/20517172/9f0695a1-f389-4097-ba00-103975625317)

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by adoin** [comment]
> Could you please provide a minimal reproduction?

Sure, minutes

**Comment by adoin** [comment]
> Could you please provide a minimal reproduction?

[code sandbox](https://codesandbox.io/p/sandbox/vue-tsc-antdv-crash-reporduce-p8yxsy)
pnpm i
npm run check

**Comment by adoin** [comment]
> > Could you please provide a minimal reproduction?
> 
> [code sandbox](https://codesandbox.io/p/sandbox/vue-tsc-antdv-crash-reporduce-p8yxsy) pnpm i npm run check

This vue-tsc crashed.
And if revert to 1.7.11 can work.
https://codesandbox.io/p/sandbox/idx-unused-nc6xlc?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A13%2C1
Just treat idx in template as unused.

**Comment by so1ve** [comment]
I'll look into this in a few days

**Comment by so1ve** [comment]
I suddenly found this is duplicate of #329 =。=

**Comment by so1ve** [comment]
I believe the first problem has been resolved and the second one is a duplication.

**Comment by adoin** [comment]
> I believe the first problem has been resolved and the second one is a duplication.

yep

**Comment by adoin** [comment]
> I believe the first problem has been resolved and the second one is a duplication.

1.8.2 Still crash.
https://codesandbox.io/p/sandbox/vue-tsc-antdv-crash-reporduce-p8yxsy?file=%2Fpackage.json%3A25%2C22

**Comment by so1ve** [comment]
Thanks for you confirmation.

**Comment by johnsoncodehk** [comment]
Closed due to unable to reproduce in latest version.
