### ISSUE TITLE
Types of generic parameters in components defined with `defineComponent` are always `unknown`

### ISSUE THREAD

**Issue by rijenkii** [vuejs/language-tools#3745]
[Playground reproduction](https://play.vuejs.org/#eNqNUk1vwjAM/StWLoA0gTZuXYe0r8N22NDgRtBUFdOFpUmUpAwJ9b/PSfkoE5t2aePn5/g5flt2a0x/XSFLWOpyK4wHh74yI65EabT1cK9L84BLoRCWVpfQ6Q+OUCjtXJ9wJ6H8hBqRPTMdNG2oAQUeSyMzjxQBpK1WSemKG84ur4acQSKF8xTNOhR35oQMjgVNv3/w08GhG7tg3uVaLUXRXzmtaPptuJCznG4UEu2r8UIrx1kCMRNymZT66zli3lZ4scfzD8w/z+ArtwkYZ2OLDu0aOTvkfGYL9E36cfKCGzofkqVeVJLYfyTf0GlZBY0N7a5SC5Ld4kW1T3EvQhVT97jxqNx+qCA0MOvI54y2Ex7zt9GPcof9YazjqqZXPHVCy0QyU2Efnq45WmkLi8gNVVqh8lDvjLIzB24ij1hZJeO/ze6m01H3nVQBLTuB6TWEPdNhNoe6Bzcj6MavqqTstZy203mw4U+vt8VCgQqtyCmcRumNhrHVxqVnG4+6vbatWf0NARAZUA==)

I have defined the same component using `<script setup>` and `defineComponent`:
```vue
// CompSetup.vue
<script setup lang="ts" generic="T">
defineProps<{ msg: T; list: T[] }>();
</script>
```
```vue
// CompDefine.vue
<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent(<T>(_: { msg: T; list: T[] }) => () => null);
</script>
```

When using them, `CompSetup` automatically infers the types of arguments, however `CompDefine` does not:
```vue
<template>
  <CompSetup :msg="123" :list="['123']" />
  <!-- Displays an error saying that `'string' is not assignable to 'number'` -->

  <CompDefine :msg="123" :list="['123']" />
  <!-- Displays no errors, when hovering over `:msg` and `:list` displays types `unknown` and `unknown[]` respectively -->
</template>
```

**Comment by s-montigny-desautels** [comment]
Should be fixed with Vue 3.4.20.

**Comment by rijenkii** [comment]
This is not really fixed: [Playground](https://play.vuejs.org/#eNqNUk1vwjAM/StWLoA0gTZuXYe0r8N22KbBjaCpKqYLS5MoSRkS6n+fk/JRJph2aePn5/g5fht2a0x/VSFLWOpyK4wHh74yI65EabT1cK9L84ALoRAWVpfQ6Q8OUCjtXB9xx6H8iBqRHTMdNG2oAQUeSyMzjxQBpK1WSemKG84ur4acQSKF8xRNOxR3ZoQMDgVNv3/w08G+G7tg3uVaLUTRXzqtaPpNuJCznG4UEu2r8UIrx1kCMRNymZT6+zli3lZ4scPzT8y/TuBLtw4YZ28WHdoVcrbP+cwW6Jv04/gF13TeJ0s9rySx/0i+o9OyChob2l2l5iS7xYtqn+JehCom7nHtUbndUEFoYNaRzxltJzzmudEPcof9YazjqqZXPHZCy0QyU2Efnq45WGkD88gNVVqh8lBvjbI1B64jj1hZJeO/ze6mk1H3g1QBLTuByTWEPdNhOoO6Bzcj6MavqqTstZy21bm34W+vt8VCgQqtyCmcROmNhjerjUtPNh51e+dt3fZc/QP5AyK/)

```vue
<template>
  <CompSetup :msg="123" :list="['123']" />
  <!-- Displays an error saying that `'string' is not assignable to 'number'` -->

  <CompDefine :msg="123" :list="['123']" />
  <!-- Displays no errors, when hovering over `:msg` and `:list` displays types `number` and `string[]` respectively -->
</template>
```

**Comment by so1ve** [comment]
This looks like a bug in volar. I'll reopen this issue.

**Comment by KermanX** [comment]
This seems to have been fixed in the latest version.
