### ISSUE TITLE
Components are not highlighted

### ISSUE THREAD

**Issue by AmitJoki** [vuejs/language-tools#3966]
With vue.vscode-typescript-vue-plugin 1.8.27 and vue.volar 1.8.27 the components were highlighted correctly in a different color (green in Dark Modern Theme).

When vue.volar updated to 2.0.4, it asked to uninstall vue.vscode-typescript-vue-plugin and I did and the components are no longer highlighted. They look like other HTML elements (blue in Dark Modern Theme).

**Comment by lazercaveman** [comment]
Same - the peek feature isn't working anymore as well (before, when pressing CMD while clicking on an import path or a component within the template, the IDE would open/redirect to the related components file).

**Comment by lazercaveman** [comment]
Since the "Take Over Mode" is now deprecated, you have to reactivate "TypeScript and JavaScript Language Features" in vs Code - after that everything should work just fine again : )

**Comment by n-ochs** [comment]
@lazercaveman - I tried this and unfortunately it did not work. For everyone else looking here, you have to search extensions for "@builtin typescript" and you will find it

**Comment by Tom-El-Egant** [comment]
Same issue here: we have a monorepo, 2 out of 3 workspaces are working fine (components are linked and fully typed), in the third workspace the components are not typed. All 3 workspaces have exactly the same nuxt.config and tsconfig.
Downgrading to v1.8.27, integrating Volar plugin and disable builtin typescript plugin solves the issue.

**Comment by mouldt** [comment]
Not sure if this is related but i get an error in the VScode Extension Host log:
TypeError: Invalid Version: 5
at new n (c:\Users\XXX\.vscode\extensions\vue.volar-2.0.4\dist\client.js:46:15557)
at hP (c:\Users\Tony\.vscode\extensions\vue.volar-2.0.4\dist\client.js:46:27441)
	at Object._P [as gte] (c:\Users\XXX\.vscode\extensions\vue.volar-2.0.4\dist\client.js:46:27782)
	at o (c:\Users\XXX\.vscode\extensions\vue.volar-2.0.4\dist\client.js:63:633)
	at async s (c:\Users\XXX\.vscode\extensions\vue.volar-2.0.4\dist\client.js:56:519)

This shows up when i open a .vue file.

**Comment by ascott18** [comment]
Coloring is sometimes working for me, but for some reason it is affected by scroll position in the document. All I'm doing in this video is scrolling up and down:

https://github.com/vuejs/language-tools/assets/5017521/42d99b22-ab8d-4204-a4a0-f7f61d75ba1b

**Comment by ascott18** [comment]
This is also somehow related to the height of the editor. Resizing the editor height without scrolling also affects this.

https://github.com/vuejs/language-tools/assets/5017521/913ca9a3-d7b9-4ac0-a40b-aee85b051609

**Comment by gabrielmaxgb** [comment]
How could it go live if would break so many things at the same time?

**Comment by frkam** [comment]
> How could it have been deployed if it would have caused so many issues simultaneously?

rolled some shit just for fun, i think

**Comment by frkam** [comment]
> How could it have been deployed if it would have caused so many issues simultaneously?

and they deprecated volar typescript... so bad. vscode feels like im coding from pentium 4 pc

**Comment by sa8ab** [comment]
@frkam You can install depricated extension
Press CTRL P to open up the command of VS code
type in `ext install Vue.vscode-typescript-vue-plugin`
Install older version on Volar. And don't forget to disable built in ts features of vs code.

**Comment by frkam** [comment]
@sa8ab thank you so much, i didn't even thin about it before this. Old vue extension with volar-ts works wonderful compared to new version

**Comment by mauriciopfl** [comment]
> Agora há um sublinhado nos componentes e a cor é a mesma das diretivas/adereços. Eu realmente prefiro o jeito antigo, quando a cor era um azul claro distinto.
> 
> Estou usando o código VS e o tema Monokai.

**### Same problem here. It was very bad this way, very messy and disorganized. Is there any way to go back to the old model?**

![image](https://github.com/vuejs/language-tools/assets/12702629/b9841018-ea8d-4510-88e6-de2820c80ffe)

**Comment by Laurelin** [comment]
Still an issue. needed to downgrade the update to 1.8.27 to get correct typing on components

**Comment by marius-mcfly** [comment]
> Still an issue. needed to downgrade the update to 1.8.27 to get correct typing on components

Same here

**Comment by manchenkoff** [comment]
FYI, with these versions everything works fine and highlights are back: 
- [Vue - Official](https://marketplace.visualstudio.com/items?itemName=Vue.volar) v2.0.7
- [JavaScript and Typescript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) v5.5.20240326

**Comment by johnsoncodehk** [comment]
Here are multiple issues mixed together:

- The issue of missing highlight for component tags should have been resolved in the latest version.

- Regarding the issue of color variation for component tag highlights, this is a design limitation of the mixed mode. Since tsserver does not have component semantic tokens, we can only use approximate class semantic tokens as a substitute, which can cause problems in some themes. We are looking for a solution, so please open a new issue for this.

- The highlight and scrolling issues have been resolved in the latest commit and will fixed in version 2.0.8.

**Comment by mapleroyal** [comment]
This is still an issue. I completely wiped everything on the machine related to vscode > rebooted > did not log in > init'd a new vue project > installed `Vue - Official` when prompted > still no component highlighting, plus the associated problems (can't cmd+click vue components/modules/imports).

**Comment by mapleroyal** [comment]
Rolling back to 2.0.24 fixes it...

**Comment by RachaunH** [comment]
You sir deserve a sticker ⭐

**Comment by jm-sky** [comment]
Sorry to bother You, but I can't get it working.
Using Windows with WSL2, VScode in WSL.
I've been trying to reinstall extension, downgrade, upgrade, change color theme - components are not highlighted.

What should I check? Where should I look?

#### Output: Vue Language Server
```
[Vue Named Pipe Client] Connected: /tmp/vue-named-pipe-2.1.10-configured-0 in 2ms
[Vue Named Pipe Client] Ready: /tmp/vue-named-pipe-2.1.10-configured-0 in 3ms
```

#### Output: TypeScript
```
2024-11-29 09:36:44.339 [info] Starting TS Server
2024-11-29 09:36:44.339 [info] Using tsserver from: /home/madeyskij/projects/portal/node_modules/typescript/lib/tsserver.js
2024-11-29 09:36:44.339 [info] <syntax> Forking...
2024-11-29 09:36:44.339 [info] <syntax> Starting...
2024-11-29 09:36:44.339 [info] <semantic> Forking...
2024-11-29 09:36:44.339 [info] <semantic> Starting...
```

**Comment by alexchexes** [comment]
> Still an issue. needed to downgrade the update to 1.8.27 to get correct typing on components

The fact that almost any issue with the official VS Code Vue extension can be resolved by downgrading to 1.8.27 should give the maintainers something to think about. Clearly, something has gone wrong with the way releases are being rolled out.

**Comment by sachasmart** [comment]
Still a problem.

**Comment by SteynGuelen** [comment]
Can confirm, still an issue. Downgrading to 2.0.24 works.

**Comment by Julbert123** [comment]
This is still an issue, I also had to downgrade straight frm 3.1.4 to 2.0.24 (I tried multiple 3.x versions)

**Comment by KazariEX** [comment]
This issue is outdated. If you are still encountering this problem (and certain that your components are correctly typed), please open a new issue with a detailed description and minimal reproduction.
