### ISSUE TITLE
2.0+ causes ts and ts-plugin to check for problems in an infinite loop

### ISSUE THREAD

**Issue by matveyson** [vuejs/language-tools#3981]
# System Info
M2 Max, Sonoma 14.2.1 (23C71)
VSCode 1.87.0 - Clean installation (vue.volar is the only marketplace extension installed)
Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js (built-in, v5.3.2)
<details>
  <summary>Output - TypeScript</summary>

```
2024-03-04 16:37:16.997 [info] Starting TS Server
2024-03-04 16:37:16.997 [info] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-04 16:37:16.997 [info] <syntax> Forking...
2024-03-04 16:37:16.997 [info] <syntax> Starting...
2024-03-04 16:37:16.997 [info] <semantic> Forking...
2024-03-04 16:37:16.997 [info] <semantic> Starting...
2024-03-04 16:37:16.997 [info] <diagnostics> Forking...
2024-03-04 16:37:16.997 [info] <diagnostics> Starting...
```
</details>
<details>
  <summary>Output - Extension Host</summary>

```
2024-03-04 16:37:16.842 [info] ExtensionService#_doActivateExtension Vue.volar, startup: false, activationEvent: 'onLanguage:vue'
2024-03-04 16:37:16.881 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'api', root cause: Vue.volar
2024-03-04 16:40:05.859 [info] Extension host terminating: renderer closed the MessagePort
2024-03-04 16:40:05.880 [error] Canceled: Canceled
	at new $ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:45885)
	at s.U (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5556)
	at z.<computed>.T.charCodeAt.z.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:3007)
	at l.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184415)
	at l.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183853)
	at f.registerCommand.description (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183177)
	at l.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184954)
	at l.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183946)
	at l.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183853)
	at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:21654)
	at w.O [as value] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:943479)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1972)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2188)
	at Object.m [as dispose] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:962791)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:968825
	at Array.forEach (<anonymous>)
	at f.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:968811)
	at u.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:3704)
	at u.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:3801)
	at u.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:945736)
	at u.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:3801)
	at o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:754)
	at w.cb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:9882)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7816
	at Array.map (<anonymous>)
	at w.Y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7803)
	at w.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:8076)
	at o.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:1513)
	at t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:9949)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6374)
	at MessagePortMain.emit (node:events:514:28)
	at Object.emit (node:electron/js2c/utility_init:2:2285) setContext undefined
2024-03-04 16:40:05.881 [error] Canceled: Canceled
	at new $ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:45885)
	at s.U (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5556)
	at z.<computed>.T.charCodeAt.z.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:3007)
	at l.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184415)
	at l.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183853)
	at f.registerCommand.description (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183177)
	at l.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184954)
	at l.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183946)
	at l.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183853)
	at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:21654)
	at set hasGitHubRepositories [as hasGitHubRepositories] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js:2:325214)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js:2:326173
	at w.value (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1050811)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1972)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2188)
	at Object.m [as dispose] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:962791)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:968825
	at Array.forEach (<anonymous>)
	at f.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:968811)
	at u.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:3704)
	at u.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:3801)
	at u.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:945736)
	at u.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:148:3801)
	at o (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:754)
	at w.cb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:9882)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7816
	at Array.map (<anonymous>)
	at w.Y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7803)
	at w.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:8076)
	at o.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:1513)
	at t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:9949)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6374)
	at MessagePortMain.emit (node:events:514:28)
	at Object.emit (node:electron/js2c/utility_init:2:2285) setContext undefined
2024-03-04 16:40:05.882 [info] Extension host with pid 11503 exiting with code 0
2024-03-04 16:40:06.469 [info] Extension host with pid 12508 started
2024-03-04 16:40:06.469 [info] Skipping acquiring lock for /Users/matveyson/Library/Application Support/Code/User/workspaceStorage/2fbaa6e59b7ea8d50226bf19566afd2d.
2024-03-04 16:40:06.501 [info] ExtensionService#_doActivateExtension Vue.volar, startup: false, activationEvent: 'onLanguage:plaintext'
2024-03-04 16:40:06.525 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-03-04 16:40:06.686 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'api', root cause: Vue.volar
2024-03-04 16:40:06.727 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-03-04 16:40:06.728 [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
2024-03-04 16:40:06.734 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-03-04 16:40:06.742 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-03-04 16:40:06.773 [info] Eager extensions activated
2024-03-04 16:40:06.779 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-03-04 16:40:06.780 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-03-04 16:40:07.087 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-03-04 16:40:08.078 [error] TypeError: Invalid Version: 5
	at new n (/Users/matveyson/.vscode/extensions/vue.volar-2.0.4/dist/client.js:46:15557)
	at hP (/Users/matveyson/.vscode/extensions/vue.volar-2.0.4/dist/client.js:46:27441)
	at Object._P [as gte] (/Users/matveyson/.vscode/extensions/vue.volar-2.0.4/dist/client.js:46:27782)
	at o (/Users/matveyson/.vscode/extensions/vue.volar-2.0.4/dist/client.js:63:633)
	at async s (/Users/matveyson/.vscode/extensions/vue.volar-2.0.4/dist/client.js:56:519)
```

</details>

## Impact
2.0+ versions are causing an endless problem-checking loop with a high CPU utilization (200+), VSCode becomes laggy.

## Temporary solution (for me)
Downgrade to 1.8.27.

## Video
https://github.com/vuejs/language-tools/assets/12140030/13300cc4-85b7-4729-a94a-88169a488a75

**Comment by matveyson** [comment]
Finally found a project that I could share, I could not reproduce it on a brand new vue/nuxt installation. However, on an old ones (especially big ones) it in 90% cases exists.
I also tried to follow the steps in your issue (installing ms-vscode.vscode-typescript-next which uses latest version of ts), but it does not fix the issue. Moreover, I've seen this bug on projects with only one tsconfig file.

Steps to reproduce:

1) VSCode + `vue.volar` (2.0+) + (optionally `ms-vscode.vscode-typescript-next` which does not fix anything)
2) Clone https://github.com/matveyson/vue-volar-issue-3981 (private, I've sent you the collaboration request)
3) Click on any `.vue` file

Attaching the ts-server log:
[log.log](https://github.com/vuejs/language-tools/files/14507304/log.log)

**Comment by johnsoncodehk** [comment]
Can you add access for @sheetalkamat?

I can't reproduce the problem in this repo on my Mac system, since this seems to be a system specific issue, I'm assuming this is related to the Node version, could you try VSCode Insiders?

**Comment by sheetalkamat** [comment]
@matveyson from the log it looks like you are using 5.3.2, you need to use nightly version of typescript as https://github.com/microsoft/TypeScript/pull/56403 was fixed for macOS and is in 5.4+  which i believe is the issue.

**Comment by matveyson** [comment]
@johnsoncodehk, added @sheetalkamat.

I installed TypeScript Nightly plugin (https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) but the issue is still present with this plugin.
However, installing VSCode Insiders **fixed** the issue for me.

**Comment by johnsoncodehk** [comment]
This may be a difference caused by different Node versions of the VSCode bundle, closed since it has been resolved by upstream.

**Comment by Gregoor** [comment]
I think I'm experiencing the same issue: https://github.com/vuejs/language-tools/issues/4519

I'm on VSCode 1.91. Is the expectation that it should be resolved now? Or with the next major version?
