### ISSUE TITLE
<script lang='tsx'> does not highlight properly unlike jsx, ts and js

### ISSUE THREAD

**Issue by Tenrys** [vuejs/language-tools#4291]
![Code_zPJXU5MNsM](https://github.com/vuejs/language-tools/assets/3979239/f47affe5-2522-44f4-beea-5bb1b7e4ce45)

**Comment by Tenrys** [comment]
it also seems like updating that tag too quickly can make volar lose track of which "language" is used, I had changed it back to tsx but it still thought I was in a js file

**Comment by lokewei** [comment]
I have the same problem

**Comment by johnsoncodehk** [comment]
This should fixed by https://github.com/microsoft/TypeScript/pull/57641 in TS 5.5.

**Comment by johnsoncodehk** [comment]
Duplicate of #3912

**Comment by Tenrys** [comment]
Not sure if I need to wait for VSCode / other extensions to update to 5.5, but trying to use the 5.5 beta in a workspace as the language server does not seem to fix the issue yet?
