### ISSUE TITLE
VSCode autocomplete not working after enabling Vue - Official extension

### ISSUE THREAD

**Issue by FlucTuAteDev** [vuejs/language-tools#5387]
### Vue - Official extension or vue-tsc version

2.2.10

### VSCode version

1.100.2

### Vue version

^3.5.15

### TypeScript version

^5.8.3

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13500
    Memory: 21.06 GB / 31.03 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 22.16.0 - /usr/local/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 10.9.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 137.0.7151.55
```

### package.json dependencies

```json
subproject:
  "devDependencies": {
    "@eslint/js": "^9.19.0",
    "@parcel/transformer-sass": "^2.6.0",
    "@types/bootstrap3-dialog": "^1.35.5",
    "@types/jquery": "^3.5.32",
    "@types/jqueryui": "^1.12.24",
    "@types/lodash": "^4.17.14",
    "@types/node": "^16.11.7",
    "@types/svg-parser": "^2.0.3",
    "concurrently": "^9.1.2",
    "eslint": "^9.19.0",
    "globals": "^15.14.0",
    "parcel": "^2.6.0",
    "prettier": "^3.4.2",
    "svgo": "^3.3.2",
    "ts-node": "^10.4.0",
    "tsc-watch": "^6.2.1",
    "typescript": "^5.8.3",
    "typescript-eslint": "^8.33.0"
  },
  "dependencies": {
    "construct-style-sheets-polyfill": "^3.1.0",
    "direction": "^2.0.1",
    "fabric": "6.5.1",
    "gifuct-js": "^2.1.2",
    "lodash": "^4.17.21",
    "paper": "^0.12.17",
    "process": "^0.11.10",
    "svg-parser": "^2.0.4",
    "tesseract.js": "^5.1.1",
    "vue": "^3.5.15",
    "xml-formatter": "^3.6.2"
  }

main project:
  "dependencies": {
    "@alenaksu/json-viewer": "2.0.0",
    "@algolia/autocomplete-js": "^1.17.6",
    "@algolia/autocomplete-plugin-recent-searches": "^1.17.7",
    "@algolia/autocomplete-theme-classic": "^1.17.7",
    "@algolia/client-search": "^5.15.0",
    "@google-cloud/vision": "^1.7.2",
    "@meilisearch/autocomplete-client": "^0.4.1",
    "@microsoft/office-js": "^1.1.90",
    "@microsoft/teams-js": "^1.6.0",
    "@mozaweb/mwicon": "^0.98.87",
    "@rwap/jquery-ui-touch-punch": "^1.0.11",
    "@sentry/browser": "^8.42.0",
    "algoliasearch": "^5.12.0",
    "altcha": "^1.4.0",
    "autoprefixer": "9.8.6",
    "autosize": "^4.0.2",
    "bootstrap-rtl": "^3.3.4",
    "bootstrap-social": "^5.1.1",
    "bootstrap3-dialog": "^1.35.4",
    "browserify": "^14.4.0",
    "chart.js": "^4.4.8",
    "codemirror": "^5.53.2",
    "compare-versions": "^3.4.0",
    "del": "^2.2.2",
    "dotenv": "8.2.0",
    "envify": "^4.1.0",
    "eonasdan-bootstrap-datetimepicker": "^4.17.49",
    "events": "^3.3.0",
    "globalthis": "^1.0.3",
    "handsontable": "14.4.0",
    "image-map-resizer": "^1.0.3",
    "jquery": "1.11.2",
    "jquery-bar-rating": "^1.2.2",
    "lazyloadxt": "^1.1.0",
    "moment": "^2.30.1",
    "moment-timezone": "^0.5.46",
    "mqtt": "^5.11.0",
    "postcss-flexibility": "^2.0.0",
    "pouchdb": "^7.2.2",
    "pouchdb-find": "^7.2.2",
    "quill": "^2.0.2",
    "retinajs": "^2.1.3",
    "rxjs": "^6.6.3",
    "sass": "^1.85.1",
    "search-insights": "^2.17.3",
    "select2": "4.0.2",
    "slick-carousel": "^1.8.1",
    "through2": "^4.0.2",
    "toastify-js": "^1.11.1",
    "transformatrix": "^1.1.1",
    "ua-parser-js": "^0.7.20",
    "unicode-bidirectional": "^2.0.5",
    "xml-writer": "^1.7.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/preset-env": "^7.12.1",
    "@eslint/js": "^9.21.0",
    "@types/chart.js": "^2.9.41",
    "@types/jquery": "^3.5.32",
    "babelify": "^10.0.0",
    "chartjs-plugin-datalabels": "^2.2.0",
    "eslint": "^9.21.0",
    "eslint-plugin-import": "^2.31.0",
    "globals": "^16.0.0",
    "gulp": "^5.0.0",
    "gulp-buffer": "^0.0.2",
    "gulp-concat": "^2.6.1",
    "gulp-concat-css": "^3.1.0",
    "gulp-cssnano": "^2.1.3",
    "gulp-filter": "^9.0.1",
    "gulp-if": "^3.0.0",
    "gulp-jsvalidate": "^6.1.0",
    "gulp-postcss": "^10.0.0",
    "gulp-rename": "^2.0.0",
    "gulp-replace": "^1.1.4",
    "gulp-rtlcss": "^2.0.0",
    "gulp-sass": "^6.0.0",
    "gulp-sourcemaps": "^3.0.0",
    "gulp-tap": "^2.0.0",
    "gulp-typescript": "^6.0.0-alpha.1",
    "gulp-uglify": "^3.0.2",
    "postcss": "^8.5.3",
    "prettier": "^3.5.3",
    "typescript": "^5.8.3",
    "typescript-eslint": "^8.33.0"
  },
```

### Steps to reproduce

I can't provide reproduction steps, and I also can't provide you with the repo because it is closed source. I've tried to create a minimal reproduction project but the error doesn't show up there. I'm assuming the problem is caused by the size of the project. But i am willing to answer any questions or provide you with logs.

### What is expected?

I have a big monorepo with a subproject inside of it that i work on. I added vue to this subproject and installed the Vue - Official extension in VSCode. It is a typescript project and when the extension is not installed the intellisense and type inferences work well, and i would expect the same after installing the extension.

### What is actually happening?

After installing the extension autocomplete and showing types on hover stops working, but 'find all references' and 'go to definition' seem to work as expected. Also sometimes on the bottom bar it shows 'analyzing \<file\> and its dependencies' indefinitely. On hover it shows 'Loading...' indefinitely.

### Any additional comments?

When disabling hybrid mode it starts working again, but vue imports fail. A temporary workaround i found is to create a vue.d.ts file with the following content:
```ts
declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}
```
That works but it isn't ideal, because now 'go to definition' opens this file instead of the imported vue file.

<details>

<summary>tsconfigs</summary>

tsconfig_base.json (main project tsconfig):
```json
{
  "compilerOptions": {
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strict": true,

    "module": "ESNext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,

    "allowJs": true,

    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,

    "target": "ESNext",

    "skipLibCheck": true
  }
}
```

tsconfig.json (subproject's):
```json
{
  "extends": "../tsconfig_base.json",
  "compilerOptions": {
    "typeRoots": ["src/type_definitions", "./node_modules/@types"],
    "noEmit": true,
    "verbatimModuleSyntax": true
  },

  "include": ["src/**/*", "../js/scripts/widgets/types"],

  "references": [{ "path": "../ts" }]
}
```

tsconfig.json (in main project's ts folder):
```json
{
    "extends": "../tsconfig_base.json",

    "compilerOptions": {
        "composite": true
    }
}
```

</details>

<details>
<summary>vue language server trace</summary>

```
[Trace - 11:28:37] Sending request 'initialize - (0)'.
Params: {
    "processId": null,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.100.2"
    },
    "locale": "en",
    "rootPath": "/home/adam/mozaweb",
    "rootUri": "file:///home/adam/mozaweb",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
            },
            "configuration": true,
            "didChangeWatchedFiles": {
                "dynamicRegistration": true,
                "relativePatternSupport": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "resolveSupport": {
                    "properties": [
                        "location.range"
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "workspaceFolders": true,
            "foldingRange": {
                "refreshSupport": true
            },
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            },
            "inlineValue": {
                "refreshSupport": true
            },
            "inlayHint": {
                "refreshSupport": true
            },
            "diagnostics": {
                "refreshSupport": true
            }
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                },
                "codeDescriptionSupport": true,
                "dataSupport": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "insertReplaceSupport": true,
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    },
                    "labelDetailsSupport": true
                },
                "insertTextMode": 2,
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                },
                "completionList": {
                    "itemDefaults": [
                        "commitCharacters",
                        "editRange",
                        "insertTextFormat",
                        "insertTextMode",
                        "data"
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    },
                    "activeParameterSupport": true
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "labelSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                },
                "honorsChangeAnnotations": true
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true,
                "rangesSupport": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true,
                "prepareSupportDefaultBehavior": 1,
                "honorsChangeAnnotations": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true,
                "foldingRangeKind": {
                    "valueSet": [
                        "comment",
                        "imports",
                        "region"
                    ]
                },
                "foldingRange": {
                    "collapsedText": false
                }
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator",
                    "decorator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false,
                "serverCancelSupport": true,
                "augmentsSyntaxTokens": true
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            },
            "typeHierarchy": {
                "dynamicRegistration": true
            },
            "inlineValue": {
                "dynamicRegistration": true
            },
            "inlayHint": {
                "dynamicRegistration": true,
                "resolveSupport": {
                    "properties": [
                        "tooltip",
                        "textEdits",
                        "label.tooltip",
                        "label.location",
                        "label.command"
                    ]
                }
            },
            "diagnostic": {
                "dynamicRegistration": true,
                "relatedDocumentSupport": false
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": true
                }
            },
            "showDocument": {
                "support": true
            },
            "workDoneProgress": true
        },
        "general": {
            "staleRequestSupport": {
                "cancel": true,
                "retryOnContentModified": [
                    "textDocument/semanticTokens/full",
                    "textDocument/semanticTokens/range",
                    "textDocument/semanticTokens/full/delta"
                ]
            },
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0",
                "allowedTags": [
                    "ul",
                    "li",
                    "p",
                    "code",
                    "blockquote",
                    "ol",
                    "h1",
                    "h2",
                    "h3",
                    "h4",
                    "h5",
                    "h6",
                    "hr",
                    "em",
                    "pre",
                    "table",
                    "thead",
                    "tbody",
                    "tr",
                    "th",
                    "td",
                    "div",
                    "del",
                    "a",
                    "strong",
                    "br",
                    "img",
                    "span"
                ]
            },
            "positionEncodings": [
                "utf-16"
            ]
        },
        "notebookDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "executionSummarySupport": true
            }
        }
    },
    "initializationOptions": {
        "typescript": {
            "tsdk": "/usr/share/code/resources/app/extensions/node_modules/typescript/lib"
        },
        "vue": {
            "hybridMode": true
        }
    },
    "trace": "verbose",
    "workspaceFolders": null
}


[Trace - 11:28:37] Received response 'initialize - (0)' in 285ms.
Result: {
    "capabilities": {
        "textDocumentSync": 2,
        "workspace": {
            "workspaceFolders": {
                "supported": true,
                "changeNotifications": true
            }
        },
        "selectionRangeProvider": true,
        "foldingRangeProvider": true,
        "linkedEditingRangeProvider": true,
        "colorProvider": true,
        "documentSymbolProvider": true,
        "documentFormattingProvider": true,
        "documentRangeFormattingProvider": true,
        "referencesProvider": true,
        "definitionProvider": true,
        "hoverProvider": true,
        "documentHighlightProvider": true,
        "renameProvider": {
            "prepareProvider": true
        },
        "documentLinkProvider": {},
        "inlayHintProvider": {},
        "completionProvider": {
            "triggerCharacters": [
                "*",
                "/",
                "-",
                ":",
                "\"",
                ".",
                "<",
                "=",
                "@",
                ">",
                "+",
                "^",
                "(",
                ")",
                "#",
                "[",
                "]",
                "$",
                "{",
                "}"
            ],
            "resolveProvider": true
        },
        "codeActionProvider": {
            "codeActionKinds": [
                "refactor"
            ],
            "resolveProvider": true
        },
        "documentOnTypeFormattingProvider": {
            "firstTriggerCharacter": ";",
            "moreTriggerCharacter": [
                "}",
                "\n"
            ]
        },
        "executeCommandProvider": {
            "commands": [
                "vue.parseSfc",
                "vue.detectNameCasing",
                "vue.convertTagsToKebabCase",
                "vue.convertTagsToPascalCase",
                "vue.convertPropsToKebabCase",
                "vue.convertPropsToCamelCase"
            ]
        },
        "experimental": {
            "autoInsertionProvider": {
                "triggerCharacters": [
                    ">",
                    "=",
                    "/",
                    "\\w",
                    "}"
                ],
                "configurationSections": [
                    [
                        "javascript.autoClosingTags",
                        "typescript.autoClosingTags",
                        "html.autoClosingTags"
                    ],
                    [
                        "html.autoCreateQuotes"
                    ],
                    [
                        "html.autoClosingTags"
                    ],
                    [
                        "vue.autoInsert.dotValue"
                    ],
                    [
                        "vue.autoInsert.bracketSpacing"
                    ]
                ]
            },
            "documentDropEditsProvider": true
        },
        "diagnosticProvider": {
            "interFileDependencies": false,
            "workspaceDiagnostics": false
        }
    }
}


[Trace - 11:28:37] Sending notification 'initialized'.
Params: {}


[Trace - 11:28:37] Sending request 'workspace/executeCommand - (1)'.
Params: {
    "command": "vue.parseSfc",
    "arguments": [
        "<script setup lang=\"ts\">\n\n</script>\n\n<template>\n    <div>halo</div>\n</template>"
    ]
}


[Trace - 11:28:37] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue",
        "languageId": "vue",
        "version": 21,
        "text": "<script setup lang=\"ts\">\n\n</script>\n\n<template>\n    <div>halo</div>\n</template>"
    }
}


[Trace - 11:28:37] Sending notification 'workspace/didChangeWorkspaceFolders'.
Params: {
    "event": {
        "added": [
            {
                "uri": "file:///home/adam/mozaweb",
                "name": "mozaweb"
            }
        ],
        "removed": []
    }
}


[Trace - 11:28:37] Sending request 'textDocument/diagnostic - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:28:37] Sending request 'workspace/executeCommand - (3)'.
Params: {
    "command": "vue.detectNameCasing",
    "arguments": [
        "file:///home/adam/mozaweb/mblite/src/App.vue"
    ]
}


[Trace - 11:28:37] Received request 'client/registerCapability - (0)'.
Params: {
    "registrations": [
        {
            "id": "3409d8df-3132-454c-b7f6-6d4a99b9b4b4",
            "method": "workspace/didChangeConfiguration",
            "registerOptions": {}
        }
    ]
}


[Trace - 11:28:37] Sending response 'client/registerCapability - (0)'. Processing request took 1ms
No result returned.


[Trace - 11:28:37] Sending request 'textDocument/documentSymbol - (4)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:28:37] Sending request 'textDocument/codeAction - (5)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 0,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 2
    }
}


[Trace - 11:28:37] Received request 'workspace/configuration - (1)'.
Params: {
    "items": [
        {
            "section": "http"
        }
    ]
}


[Trace - 11:28:37] Sending response 'workspace/configuration - (1)'. Processing request took 0ms
Result: [
    {
        "useLocalProxyConfiguration": true,
        "electronFetch": false,
        "proxy": "",
        "proxyStrictSSL": true,
        "proxyKerberosServicePrincipal": "",
        "noProxy": [],
        "proxyAuthorization": null,
        "proxySupport": "override",
        "systemCertificates": true,
        "experimental": {
            "systemCertificatesV2": false
        },
        "fetchAdditionalSupport": true
    }
]


[Trace - 11:28:37] Sending request 'textDocument/documentColor - (6)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:28:37] Received response 'workspace/executeCommand - (1)' in 3ms.
No result returned.


[Trace - 11:28:37] Sending request 'textDocument/documentLink - (7)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:28:37] Sending request 'textDocument/inlayHint - (8)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 6,
            "character": 11
        }
    }
}


[Trace - 11:28:37] Received response 'workspace/executeCommand - (3)' in 17ms.
Result: {
    "tag": [],
    "attr": []
}


[Trace - 11:28:37] Received response 'textDocument/documentSymbol - (4)' in 26ms.
Result: [
    {
        "name": "template",
        "kind": 2,
        "range": {
            "start": {
                "line": 4,
                "character": 0
            },
            "end": {
                "line": 6,
                "character": 11
            }
        },
        "selectionRange": {
            "start": {
                "line": 4,
                "character": 0
            },
            "end": {
                "line": 4,
                "character": 10
            }
        },
        "children": [
            {
                "name": "div",
                "kind": 8,
                "range": {
                    "start": {
                        "line": 5,
                        "character": 4
                    },
                    "end": {
                        "line": 5,
                        "character": 19
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 5,
                        "character": 4
                    },
                    "end": {
                        "line": 5,
                        "character": 19
                    }
                }
            }
        ]
    },
    {
        "name": "script setup",
        "kind": 2,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 2,
                "character": 9
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 24
            }
        }
    }
]


[Trace - 11:28:37] Received response 'textDocument/diagnostic - (2)' in 27ms.
Result: {
    "kind": "full",
    "items": []
}


TSServer project ready: /home/adam/mozaweb/mblite/tsconfig.json
[Trace - 11:28:37] Received response 'textDocument/codeAction - (5)' in 42ms.
Result: []


[Trace - 11:28:37] Received response 'textDocument/documentColor - (6)' in 41ms.
No result returned.


[Trace - 11:28:37] Received response 'textDocument/documentLink - (7)' in 40ms.
Result: []


[Trace - 11:28:37] Received request 'workspace/configuration - (2)'.
Params: {
    "items": [
        {
            "section": "vue.inlayHints.missingProps"
        }
    ]
}


[Trace - 11:28:37] Sending response 'workspace/configuration - (2)'. Processing request took 0ms
Result: [
    false
]


[Trace - 11:28:37] Received response 'textDocument/inlayHint - (8)' in 41ms.
Result: []


[Trace - 11:28:37] Sending request 'textDocument/foldingRange - (9)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:28:37] Received response 'textDocument/foldingRange - (9)' in 11ms.
Result: [
    {
        "startLine": 0,
        "endLine": 1
    },
    {
        "startLine": 4,
        "endLine": 5
    }
]


[Trace - 11:28:37] Received request 'workspace/inlayHint/refresh - (3)'.
[Trace - 11:28:37] Sending response 'workspace/inlayHint/refresh - (3)'. Processing request took 0ms
No result returned.


[Trace - 11:28:37] Received request 'workspace/diagnostic/refresh - (4)'.
[Trace - 11:28:37] Sending response 'workspace/diagnostic/refresh - (4)'. Processing request took 0ms
No result returned.


[Trace - 11:28:37] Sending request 'textDocument/diagnostic - (10)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:28:37] Received response 'textDocument/diagnostic - (10)' in 11ms.
Result: {
    "kind": "full",
    "items": []
}


[Trace - 11:28:37] Sending request 'textDocument/documentSymbol - (11)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:28:37] Received response 'textDocument/documentSymbol - (11)' in 1ms.
Result: [
    {
        "name": "template",
        "kind": 2,
        "range": {
            "start": {
                "line": 4,
                "character": 0
            },
            "end": {
                "line": 6,
                "character": 11
            }
        },
        "selectionRange": {
            "start": {
                "line": 4,
                "character": 0
            },
            "end": {
                "line": 4,
                "character": 10
            }
        },
        "children": [
            {
                "name": "div",
                "kind": 8,
                "range": {
                    "start": {
                        "line": 5,
                        "character": 4
                    },
                    "end": {
                        "line": 5,
                        "character": 19
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 5,
                        "character": 4
                    },
                    "end": {
                        "line": 5,
                        "character": 19
                    }
                }
            }
        ]
    },
    {
        "name": "script setup",
        "kind": 2,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 2,
                "character": 9
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 24
            }
        }
    }
]


[Trace - 11:28:37] Sending request 'textDocument/inlayHint - (12)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 6,
            "character": 11
        }
    }
}


[Trace - 11:28:37] Received response 'textDocument/inlayHint - (12)' in 1ms.
Result: []


[Trace - 11:29:24] Sending request 'textDocument/documentColor - (13)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:29:24] Sending request 'textDocument/codeAction - (14)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 0,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 2
    }
}


[Trace - 11:29:24] Received response 'textDocument/documentColor - (13)' in 1ms.
No result returned.


[Trace - 11:29:24] Sending request 'workspace/executeCommand - (15)'.
Params: {
    "command": "vue.parseSfc",
    "arguments": [
        "<script setup lang=\"ts\">\n\n</script>\n\n<template>\n    <div>halo</div>\n</template>"
    ]
}


[Trace - 11:29:24] Sending request 'workspace/executeCommand - (16)'.
Params: {
    "command": "vue.detectNameCasing",
    "arguments": [
        "file:///home/adam/mozaweb/mblite/src/App.vue"
    ]
}


[Trace - 11:29:24] Sending request 'textDocument/documentSymbol - (17)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:29:24] Received response 'textDocument/codeAction - (14)' in 3ms.
Result: []


[Trace - 11:29:24] Received response 'workspace/executeCommand - (15)' in 2ms.
Result: {
    "descriptor": {
        "filename": "anonymous.vue",
        "source": "<script setup lang=\"ts\">\n\n</script>\n\n<template>\n    <div>halo</div>\n</template>",
        "comments": [],
        "template": {
            "type": "template",
            "content": "\n    <div>halo</div>\n",
            "loc": {
                "source": "\n    <div>halo</div>\n",
                "start": {
                    "column": 11,
                    "line": 5,
                    "offset": 47
                },
                "end": {
                    "column": 1,
                    "line": 7,
                    "offset": 68
                }
            },
            "attrs": {}
        },
        "script": null,
        "scriptSetup": {
            "type": "script",
            "content": "\n\n",
            "loc": {
                "source": "\n\n",
                "start": {
                    "column": 25,
                    "line": 1,
                    "offset": 24
                },
                "end": {
                    "column": 1,
                    "line": 3,
                    "offset": 26
                }
            },
            "attrs": {
                "setup": true,
                "lang": "ts"
            },
            "setup": true,
            "lang": "ts"
        },
        "styles": [],
        "customBlocks": [],
        "cssVars": [],
        "slotted": false
    },
    "errors": []
}


[Trace - 11:29:24] Received response 'workspace/executeCommand - (16)' in 3ms.
Result: {
    "tag": [],
    "attr": []
}


[Trace - 11:29:24] Received response 'textDocument/documentSymbol - (17)' in 2ms.
Result: [
    {
        "name": "template",
        "kind": 2,
        "range": {
            "start": {
                "line": 4,
                "character": 0
            },
            "end": {
                "line": 6,
                "character": 11
            }
        },
        "selectionRange": {
            "start": {
                "line": 4,
                "character": 0
            },
            "end": {
                "line": 4,
                "character": 10
            }
        },
        "children": [
            {
                "name": "div",
                "kind": 8,
                "range": {
                    "start": {
                        "line": 5,
                        "character": 4
                    },
                    "end": {
                        "line": 5,
                        "character": 19
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 5,
                        "character": 4
                    },
                    "end": {
                        "line": 5,
                        "character": 19
                    }
                }
            }
        ]
    },
    {
        "name": "script setup",
        "kind": 2,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 2,
                "character": 9
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 24
            }
        }
    }
]


[Trace - 11:29:24] Sending request 'textDocument/inlayHint - (18)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 6,
            "character": 11
        }
    }
}


[Trace - 11:29:24] Sending request 'textDocument/documentLink - (19)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:29:24] Received response 'textDocument/inlayHint - (18)' in 1ms.
Result: []


[Trace - 11:29:24] Received response 'textDocument/documentLink - (19)' in 3ms.
Result: []


[Trace - 11:29:24] Sending request 'textDocument/foldingRange - (20)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:29:24] Received response 'textDocument/foldingRange - (20)' in 1ms.
Result: [
    {
        "startLine": 0,
        "endLine": 1
    },
    {
        "startLine": 4,
        "endLine": 5
    }
]


[Trace - 11:29:24] Sending request 'textDocument/documentSymbol - (21)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    }
}


[Trace - 11:29:24] Received response 'textDocument/documentSymbol - (21)' in 2ms.
Result: [
    {
        "name": "template",
        "kind": 2,
        "range": {
            "start": {
                "line": 4,
                "character": 0
            },
            "end": {
                "line": 6,
                "character": 11
            }
        },
        "selectionRange": {
            "start": {
                "line": 4,
                "character": 0
            },
            "end": {
                "line": 4,
                "character": 10
            }
        },
        "children": [
            {
                "name": "div",
                "kind": 8,
                "range": {
                    "start": {
                        "line": 5,
                        "character": 4
                    },
                    "end": {
                        "line": 5,
                        "character": 19
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 5,
                        "character": 4
                    },
                    "end": {
                        "line": 5,
                        "character": 19
                    }
                }
            }
        ]
    },
    {
        "name": "script setup",
        "kind": 2,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 2,
                "character": 9
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 24
            }
        }
    }
]


[Trace - 11:29:25] Sending request 'textDocument/codeAction - (22)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    },
    "range": {
        "start": {
            "line": 6,
            "character": 11
        },
        "end": {
            "line": 6,
            "character": 11
        }
    },
    "context": {
        "diagnostics": [],
        "triggerKind": 2
    }
}


[Trace - 11:29:25] Received response 'textDocument/codeAction - (22)' in 2ms.
Result: []


[Trace - 11:29:32] Sending request 'textDocument/inlayHint - (23)'.
Params: {
    "textDocument": {
        "uri": "file:///home/adam/mozaweb/mblite/src/App.vue"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 6,
            "character": 11
        }
    }
}


[Trace - 11:29:32] Received response 'textDocument/inlayHint - (23)' in 1ms.
Result: []


[Trace - 11:29:53] Sending request 'workspace/executeCommand - (24)'.
Params: {
    "command": "vue.parseSfc",
    "arguments": [
        "<script setup lang=\"ts\">\n\n</script>\n\n<template>\n    <div>halo</div>\n</template>"
    ]
}


[Trace - 11:29:53] Sending request 'workspace/executeCommand - (25)'.
Params: {
    "command": "vue.detectNameCasing",
    "arguments": [
        "file:///home/adam/mozaweb/mblite/src/App.vue"
    ]
}


[Trace - 11:29:53] Received response 'workspace/executeCommand - (24)' in 0ms.
Result: {
    "descriptor": {
        "filename": "anonymous.vue",
        "source": "<script setup lang=\"ts\">\n\n</script>\n\n<template>\n    <div>halo</div>\n</template>",
        "comments": [],
        "template": {
            "type": "template",
            "content": "\n    <div>halo</div>\n",
            "loc": {
                "source": "\n    <div>halo</div>\n",
                "start": {
                    "column": 11,
                    "line": 5,
                    "offset": 47
                },
                "end": {
                    "column": 1,
                    "line": 7,
                    "offset": 68
                }
            },
            "attrs": {}
        },
        "script": null,
        "scriptSetup": {
            "type": "script",
            "content": "\n\n",
            "loc": {
                "source": "\n\n",
                "start": {
                    "column": 25,
                    "line": 1,
                    "offset": 24
                },
                "end": {
                    "column": 1,
                    "line": 3,
                    "offset": 26
                }
            },
            "attrs": {
                "setup": true,
                "lang": "ts"
            },
            "setup": true,
            "lang": "ts"
        },
        "styles": [],
        "customBlocks": [],
        "cssVars": [],
        "slotted": false
    },
    "errors": []
}


[Trace - 11:29:53] Received response 'workspace/executeCommand - (25)' in 1ms.
Result: {
    "tag": [],
    "attr": []
}
```
</details>

**Comment by FlucTuAteDev** [comment]
> Please try v3.0 alpha. [#5261](https://github.com/vuejs/language-tools/issues/5261)

The issue still persists

**Comment by FlucTuAteDev** [comment]
Any updates on this? Now that 3.0 was released I can't disable hybrid mode anymore. 
But I think i found the cause of my problem: when setting the `TS Server: Use Syntax Server` option to `never` in VSCode the extension works as expected. Could this be a bug related to that setting?

**Comment by johnsoncodehk** [comment]
What is your `typescript.tsserver.useSyntaxServer` set before?

If it was "always", most features stopping working is expected, as the server will not have any semantic information.

**Comment by FlucTuAteDev** [comment]
> What is your `typescript.tsserver.useSyntaxServer` set before?
> 
> If it was "always", most features stopping working is expected, as the server will not have any semantic information.

It was on auto

**Comment by johnsoncodehk** [comment]
Can you provide the following information?

1. The VSCode userspace settings when reproducing the problem (execute the "Preferences: Open User Settings (JSON)" command)
2. The VSCode workspace settings when reproducing the problem (execute the "Preferences: Open Workspace Settings (JSON)" command)
3. The VSCode version
4. Project TS version

**Comment by FlucTuAteDev** [comment]
<details>
<summary>Userspace Settings</summary>

```json
{
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "workbench.editor.showTabs": "single",
  "zenMode.showTabs": "single",
  "workbench.sideBar.location": "right",
  "workbench.iconTheme": "material-icon-theme",
  "window.zoomPerWindow": false,
  "workbench.colorTheme": "Material Theme Darker High Contrast",
  "workbench.colorCustomizations": {
    "[Material Theme Darker High Contrast]": {
      "activityBarBadge.background": "#FFA000",
      "activityBar.activeBorder": "#FFA000",
      "list.activeSelectionForeground": "#FFA000",
      "list.inactiveSelectionForeground": "#FFA000",
      "list.highlightForeground": "#FFA000",
      "scrollbarSlider.activeBackground": "#FFA00050",
      "editorSuggestWidget.highlightForeground": "#FFA000",
      "textLink.foreground": "#FFA000",
      "progressBar.background": "#FFA000",
      "pickerGroup.foreground": "#FFA000",
      "tab.activeBorder": "#FFA000",
      "notificationLink.foreground": "#FFA000",
      "editorWidget.resizeBorder": "#FFA000",
      "editorWidget.border": "#FFA000",
      "settings.modifiedItemIndicator": "#FFA000",
      "settings.headerForeground": "#FFA000",
      "panelTitle.activeBorder": "#FFA000",
      "breadcrumb.activeSelectionForeground": "#FFA000",
      "menu.selectionForeground": "#FFA000",
      "menubar.selectionForeground": "#FFA000",
      "editor.findMatchBorder": "#FFA000",
      "selection.background": "#FFA00040",
      "statusBarItem.remoteBackground": "#FFA000"
    }
  },
  "material-icon-theme.files.color": "#90a4ae",
  "materialTheme.accent": "Yellow",
  "editor.minimap.enabled": false,
  "php.validate.executablePath": "/usr/bin/php",
  "Laravel.phpEnvironment": "local",
  "editor.inlayHints.enabled": "off",
  "editor.codeLens": false,
  "intelliphp.inlineSuggestionsEnabled": false,
  "php.codeActions.enabled": false,
  "editor.formatOnSave": true,
  "eslint.format.enable": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.codeActionsOnSave": {
    "source.organizeImports": "explicit",
    "source.fixAll": "always"
  },
  "git.autofetch": true,
  "vue.server.hybridMode": false,
  "vscode_custom_css.imports": [
    "file:///home/adam/.vscode/pretty-ts-errors-hack.css"
  ],
  "gitlens.graph.dimMergeCommits": true,
  "diffEditor.ignoreTrimWhitespace": false,
  "gitlens.graph.onlyFollowFirstParent": true,
  "typescript.tsserver.log": "off",
  "window.zoomLevel": 1,
  "typescript.disableAutomaticTypeAcquisition": true,
  "typescript.experimental.expandableHover": false,
  "typescript.tsserver.enableRegionDiagnostics": false,
  "typescript.validate.enable": false
}
```
</details>

<details>
<summary>Workspace Settings</summary>

```json
{
    "typescript.tsserver.log": "verbose",
    "vue.server.hybridMode": false
}
```
</details>

VSCode version: 1.101.2
TS version in the subrepo: 5.8.3
TS verison in the monorepo: 5.8.2

**Comment by jan-paulus** [comment]
Any update on this? I'm facing the same or similar issue on neovim.

Found a workaround by installing vue-language-server  [v2.2.8](https://github.com/vuejs/language-tools/releases/tag/v2.2.8).

For all neovim users, this can be done by:
```
:MasonUninstall vue-language-server
:MasonInstall vue-language-server@2.2.8
```

**Comment by johnsoncodehk** [comment]
@jan-paulus See #5456.

**Comment by FlucTuAteDev** [comment]
Any updates? Turning off `useSyntaxServer` doesn't fully fix the issue. Now opening files in the root project hang the ts server. I may have found a clue why this could be happening. This is the relevant section in the ts server log:
<details>
<summary>Relevant section</summary>

```
Info 1304 [17:07:20.393] event:
    {"seq":0,"type":"event","event":"projectLoadingFinish","body":{"projectName":"/home/adam/mozaweb/tsconfig.json"}}
Info 1305 [17:07:20.393] event:
    {"seq":0,"type":"event","event":"telemetry","body":{"telemetryEventName":"projectInfo","payload":{"projectId":"d79f2382bbe6d7fc0a60ee0fa22e6a7a0973fe73076b25a19159328d28d63d3a","fileStats":{"js":0,"jsSize":0,"jsx":0,"jsxSize":0,"ts":58,"tsSize":246942,"tsx":0,"tsxSize":0,"dts":272,"dtsSize":5902262,"deferred":0,"deferredSize":0},"compilerOptions":{"noFallthroughCasesInSwitch":true,"noImplicitAny":true,"noImplicitOverride":true,"noImplicitReturns":true,"noImplicitThis":true,"noUnusedLocals":true,"noUnusedParameters":true,"strict":true,"module":"esnext","moduleResolution":"bundler","moduleDetection":"force","resolveJsonModule":true,"verbatimModuleSyntax":true,"allowJs":true,"esModuleInterop":true,"forceConsistentCasingInFileNames":true,"target":"esnext","skipLibCheck":true,"noEmit":true,"typeRoots":["",""],"experimentalDecorators":true},"typeAcquisition":{"enable":false,"include":false,"exclude":false},"extends":true,"files":false,"include":true,"exclude":true,"compileOnSave":false,"configFileName":"tsconfig.json","projectType":"configured","languageServiceEnabled":true,"version":"5.8.3"}}}
Info 1306 [17:07:20.394] event:
    {"seq":0,"type":"event","event":"configFileDiag","body":{"triggerFile":"/home/adam/mozaweb/js/scripts/mozaik.js","configFile":"/home/adam/mozaweb/tsconfig.json","diagnostics":[]}}
Info 1307 [17:07:20.394] getConfigFileNameForFile:: File: /home/adam/mozaweb/tsconfig.json ProjectRootPath: /home/adam/mozaweb:: Result: undefined
Info 1308 [17:07:20.394] Creating InferredProject: /dev/null/inferredProject1*, currentDirectory: /home/adam/mozaweb
Info 1309 [17:07:20.394] Loading global plugin vue-typescript-plugin-pack
Info 1310 [17:07:20.394] Enabling plugin vue-typescript-plugin-pack from candidate paths: /home/adam/.vscode/extensions/vue.volar-3.0.1,/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js/../../..
Info 1311 [17:07:20.394] Loading vue-typescript-plugin-pack from /home/adam/.vscode/extensions/vue.volar-3.0.1 (resolved to /home/adam/.vscode/extensions/vue.volar-3.0.1/node_modules)
```

</details>

This is the end of the log and nothing happens after this. This suggests to me that when inferred projects are created something goes wrong when loading vue-typescript-plugin-pack maybe? When turning off the extension the same inferred project is created and it works just fine.

**Comment by FlucTuAteDev** [comment]
> Any updates? Turning off `useSyntaxServer` doesn't fully fix the issue. Now opening files in the root project hang the ts server. I may have found a clue why this could be happening. This is the relevant section in the ts server log:
> 
> Relevant section
> This is the end of the log and nothing happens after this. This suggests to me that when inferred projects are created something goes wrong when loading vue-typescript-plugin-pack maybe? When turning off the extension the same inferred project is created and it works just fine.

So i found out that inferred projects are created when the file is not included in the tsconfig. I made it so that all my js files are also included in the tsconfig and now it seems to work. But this could be a bug related to inferred projects.

**Comment by yst311** [comment]
The only solution that worked for me at the moment is to install specific version: **v3.0.1**! The later versions all broke the Intellisense.

**Comment by SergeGWest** [comment]
> ### Vue - Official extension or vue-tsc version
> 2.2.10
> 
> ### VSCode version
> 1.100.2
> 
> ### Vue version
> ^3.5.15
> 
> ### TypeScript version
> ^5.8.3
> 
> ### System Info
> System:
>     OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
>     CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13500
>     Memory: 21.06 GB / 31.03 GB
>     Container: Yes
>     Shell: 5.2.15 - /bin/bash
>   Binaries:
>     Node: 22.16.0 - /usr/local/bin/node
>     Yarn: 1.22.22 - ~/.yarn/bin/yarn
>     npm: 10.9.2 - /usr/local/bin/npm
>   Browsers:
>     Chrome: 137.0.7151.55
> ### package.json dependencies
> subproject:
>   "devDependencies": {
>     "@eslint/js": "^9.19.0",
>     "@parcel/transformer-sass": "^2.6.0",
>     "@types/bootstrap3-dialog": "^1.35.5",
>     "@types/jquery": "^3.5.32",
>     "@types/jqueryui": "^1.12.24",
>     "@types/lodash": "^4.17.14",
>     "@types/node": "^16.11.7",
>     "@types/svg-parser": "^2.0.3",
>     "concurrently": "^9.1.2",
>     "eslint": "^9.19.0",
>     "globals": "^15.14.0",
>     "parcel": "^2.6.0",
>     "prettier": "^3.4.2",
>     "svgo": "^3.3.2",
>     "ts-node": "^10.4.0",
>     "tsc-watch": "^6.2.1",
>     "typescript": "^5.8.3",
>     "typescript-eslint": "^8.33.0"
>   },
>   "dependencies": {
>     "construct-style-sheets-polyfill": "^3.1.0",
>     "direction": "^2.0.1",
>     "fabric": "6.5.1",
>     "gifuct-js": "^2.1.2",
>     "lodash": "^4.17.21",
>     "paper": "^0.12.17",
>     "process": "^0.11.10",
>     "svg-parser": "^2.0.4",
>     "tesseract.js": "^5.1.1",
>     "vue": "^3.5.15",
>     "xml-formatter": "^3.6.2"
>   }
> 
> main project:
>   "dependencies": {
>     "@alenaksu/json-viewer": "2.0.0",
>     "@algolia/autocomplete-js": "^1.17.6",
>     "@algolia/autocomplete-plugin-recent-searches": "^1.17.7",
>     "@algolia/autocomplete-theme-classic": "^1.17.7",
>     "@algolia/client-search": "^5.15.0",
>     "@google-cloud/vision": "^1.7.2",
>     "@meilisearch/autocomplete-client": "^0.4.1",
>     "@microsoft/office-js": "^1.1.90",
>     "@microsoft/teams-js": "^1.6.0",
>     "@mozaweb/mwicon": "^0.98.87",
>     "@rwap/jquery-ui-touch-punch": "^1.0.11",
>     "@sentry/browser": "^8.42.0",
>     "algoliasearch": "^5.12.0",
>     "altcha": "^1.4.0",
>     "autoprefixer": "9.8.6",
>     "autosize": "^4.0.2",
>     "bootstrap-rtl": "^3.3.4",
>     "bootstrap-social": "^5.1.1",
>     "bootstrap3-dialog": "^1.35.4",
>     "browserify": "^14.4.0",
>     "chart.js": "^4.4.8",
>     "codemirror": "^5.53.2",
>     "compare-versions": "^3.4.0",
>     "del": "^2.2.2",
>     "dotenv": "8.2.0",
>     "envify": "^4.1.0",
>     "eonasdan-bootstrap-datetimepicker": "^4.17.49",
>     "events": "^3.3.0",
>     "globalthis": "^1.0.3",
>     "handsontable": "14.4.0",
>     "image-map-resizer": "^1.0.3",
>     "jquery": "1.11.2",
>     "jquery-bar-rating": "^1.2.2",
>     "lazyloadxt": "^1.1.0",
>     "moment": "^2.30.1",
>     "moment-timezone": "^0.5.46",
>     "mqtt": "^5.11.0",
>     "postcss-flexibility": "^2.0.0",
>     "pouchdb": "^7.2.2",
>     "pouchdb-find": "^7.2.2",
>     "quill": "^2.0.2",
>     "retinajs": "^2.1.3",
>     "rxjs": "^6.6.3",
>     "sass": "^1.85.1",
>     "search-insights": "^2.17.3",
>     "select2": "4.0.2",
>     "slick-carousel": "^1.8.1",
>     "through2": "^4.0.2",
>     "toastify-js": "^1.11.1",
>     "transformatrix": "^1.1.1",
>     "ua-parser-js": "^0.7.20",
>     "unicode-bidirectional": "^2.0.5",
>     "xml-writer": "^1.7.0"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.12.3",
>     "@babel/preset-env": "^7.12.1",
>     "@eslint/js": "^9.21.0",
>     "@types/chart.js": "^2.9.41",
>     "@types/jquery": "^3.5.32",
>     "babelify": "^10.0.0",
>     "chartjs-plugin-datalabels": "^2.2.0",
>     "eslint": "^9.21.0",
>     "eslint-plugin-import": "^2.31.0",
>     "globals": "^16.0.0",
>     "gulp": "^5.0.0",
>     "gulp-buffer": "^0.0.2",
>     "gulp-concat": "^2.6.1",
>     "gulp-concat-css": "^3.1.0",
>     "gulp-cssnano": "^2.1.3",
>     "gulp-filter": "^9.0.1",
>     "gulp-if": "^3.0.0",
>     "gulp-jsvalidate": "^6.1.0",
>     "gulp-postcss": "^10.0.0",
>     "gulp-rename": "^2.0.0",
>     "gulp-replace": "^1.1.4",
>     "gulp-rtlcss": "^2.0.0",
>     "gulp-sass": "^6.0.0",
>     "gulp-sourcemaps": "^3.0.0",
>     "gulp-tap": "^2.0.0",
>     "gulp-typescript": "^6.0.0-alpha.1",
>     "gulp-uglify": "^3.0.2",
>     "postcss": "^8.5.3",
>     "prettier": "^3.5.3",
>     "typescript": "^5.8.3",
>     "typescript-eslint": "^8.33.0"
>   },
> ### Steps to reproduce
> I can't provide reproduction steps, and I also can't provide you with the repo because it is closed source. I've tried to create a minimal reproduction project but the error doesn't show up there. I'm assuming the problem is caused by the size of the project. But i am willing to answer any questions or provide you with logs.
> 
> ### What is expected?
> I have a big monorepo with a subproject inside of it that i work on. I added vue to this subproject and installed the Vue - Official extension in VSCode. It is a typescript project and when the extension is not installed the intellisense and type inferences work well, and i would expect the same after installing the extension.
> 
> ### What is actually happening?
> After installing the extension autocomplete and showing types on hover stops working, but 'find all references' and 'go to definition' seem to work as expected. Also sometimes on the bottom bar it shows 'analyzing <file> and its dependencies' indefinitely. On hover it shows 'Loading...' indefinitely.
> 
> ### Link to minimal reproduction
> _No response_
> 
> ### Any additional comments?
> When disabling hybrid mode it starts working again, but vue imports fail. A temporary workaround i found is to create a vue.d.ts file with the following content:
> 
> declare module '*.vue' {
>   import type { DefineComponent } from 'vue'
>   const component: DefineComponent<{}, {}, any>
>   export default component
> }
> That works but it isn't ideal, because now 'go to definition' opens this file instead of the imported vue file.
> 
> tsconfigs
> vue language server trace

Are you running docker, and docker being the one installing node modules (as root) ?
I have been facing similar issues since 3.0.2, and was stuck with using 2.X (as 3.0.1 was crshing wsl connection as well).

So today I tried installing node_modules directly, not via docker, and the issues disappeared. So probably something related to node_modules permissions

cc @johnsoncodehk

**Comment by pm0u** [comment]
I am currently experiencing this after updating to 3.0.8, I am unsure what version i was using before.



> What is your `typescript.tsserver.useSyntaxServer` set before?
> 
> If it was "always", most features stopping working is expected, as the server will not have any semantic information.

Per this, setting to "never" seems to allow the language server to work in Vue SFC, but I'm not sure if there are other impacts. Setting to "auto", it breaks.

with it on auto/unset - there isn't anything in the TS server logs, just a sigterm.

The VS language server logs are flooded with this, even when just idle (verbose logging)

```
Trace - 1:05:56 PM] Sending request 'textDocument/foldingRange - (238)'.
Params: {
    "textDocument": {
        "uri": "file:///####.vue"
    }
}


[Trace - 1:05:56 PM] Received response 'textDocument/foldingRange - (238)' in 1ms.
Result: [
    {
        "startLine": 2,
        "endLine": 9
    },
    {
        "startLine": 12,
        "endLine": 18
    },
    {
        "startLine": 11,
        "endLine": 19
    },
    {
        "startLine": 1,
        "endLine": 20
    },
    {
        "startLine": 25,
        "endLine": 30,
        "startCharacter": 0,
        "endCharacter": 37,
        "kind": "imports"
    },
    {
        "startLine": 34,
        "endLine": 34,
        "startCharacter": 5,
        "endCharacter": 5
    },
    {
        "startLine": 34,
        "endLine": 35,
        "startCharacter": 33,
        "endCharacter": 19
    },
    {
        "startLine": 38,
        "endLine": 39,
        "startCharacter": 27,
        "endCharacter": 37
    },
    {
        "startLine": 38,
        "endLine": 39,
        "startCharacter": 33,
        "endCharacter": 37
    },
    {
        "startLine": 42,
        "endLine": 44,
        "startCharacter": 0,
        "endCharacter": 3,
        "kind": "comment"
    },
    {
        "startLine": 46,
        "endLine": 55,
        "startCharacter": 32,
        "endCharacter": 34
    },
    {
        "startLine": 47,
        "endLine": 48,
        "startCharacter": 50,
        "endCharacter": 34
    },
    {
        "startLine": 50,
        "endLine": 53,
        "startCharacter": 45,
        "endCharacter": 5
    },
    {
        "startLine": 51,
        "endLine": 52,
        "startCharacter": 55,
        "endCharacter": 39
    },
    {
        "startLine": 55,
        "endLine": 55,
        "startCharacter": 9,
        "endCharacter": 9
    },
    {
        "startLine": 58,
        "endLine": 72,
        "startCharacter": 37,
        "endCharacter": 3
    },
    {
        "startLine": 59,
        "endLine": 71,
        "startCharacter": 16,
        "endCharacter": 5
    },
    {
        "startLine": 60,
        "endLine": 64,
        "startCharacter": 4,
        "endCharacter": 8
    },
    {
        "startLine": 62,
        "endLine": 63,
        "startCharacter": 12,
        "endCharacter": 42
    },
    {
        "startLine": 66,
        "endLine": 70,
        "startCharacter": 4,
        "endCharacter": 8
    },
    {
        "startLine": 68,
        "endLine": 69,
        "startCharacter": 21,
        "endCharacter": 43
    },
    {
        "startLine": 75,
        "endLine": 89,
        "startCharacter": 29,
        "endCharacter": 3
    },
    {
        "startLine": 76,
        "endLine": 88,
        "startCharacter": 16,
        "endCharacter": 5
    },
    {
        "startLine": 77,
        "endLine": 81,
        "startCharacter": 4,
        "endCharacter": 8
    },
    {
        "startLine": 79,
        "endLine": 80,
        "startCharacter": 12,
        "endCharacter": 42
    },
    {
        "startLine": 83,
        "endLine": 87,
        "startCharacter": 4,
        "endCharacter": 8
    },
    {
        "startLine": 85,
        "endLine": 86,
        "startCharacter": 21,
        "endCharacter": 43
    },
    {
        "startLine": 91,
        "endLine": 93,
        "startCharacter": 0,
        "endCharacter": 3,
        "kind": "comment"
    },
    {
        "startLine": 0,
        "endLine": 21
    },
    {
        "startLine": 24,
        "endLine": 93
    }
]
```

Edit: Does not happen with 3.0.6, does with 3.0.7 - maybe this is unrelated then, but the fix seems to be the same.

**Comment by jellebreuer** [comment]
same, as soon as i go to 3.0.7 infine loop of textDocument/foldingRange

**Comment by ascott18** [comment]
Also getting infinite spam of `textDocument/foldingRange` on 3.0.7 - 3.1.1. Reverting to 3.0.6 fixes this.

"typescript.tsserver.useSyntaxServer": "auto"
VSC 1.105.1
Windows 11
Typescript 5.9.3

**Comment by george-kuanli-peng** [comment]
"Go to definition" does not work for me recently.

Reverting to `3.0.6` does not fix this, but reverting to `3.0.0` does.

**Comment by johnsoncodehk** [comment]
> Any updates? Turning off `useSyntaxServer` doesn't fully fix the issue. Now opening files in the root project hang the ts server. I may have found a clue why this could be happening. This is the relevant section in the ts server log:

Based on the description, this is likely fixed by https://github.com/vuejs/language-tools/commit/b3a39de86d46d96dc35e8b0e6f2049724b041c7a, see https://github.com/vuejs/language-tools/issues/5598#issuecomment-3204188360.

**Comment by plastic041** [comment]
This issue still happens in 3.2.5. Last working version is 3.1.5.

<img width="445" height="172" alt="Image" src="https://github.com/user-attachments/assets/40dc2e7a-d203-45c7-aba3-96a58d21df2f" />

Happens with empty user and workspace settings.
