### ISSUE TITLE
VSCode crash in devcontainers since volar 3.0.0

### ISSUE THREAD

**Issue by NGPixel** [vuejs/language-tools#5478]
### Vue - Official extension or vue-tsc version

3.0.1

### VSCode version

1.101.2

### Vue version

3.4.21

### TypeScript version

N/A

### System Info

```shell
System:
    OS: Linux 6.6 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 18.32 GB / 23.47 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 16.20.2 - /usr/bin/node
    Yarn: 3.2.2 - /usr/bin/yarn
    npm: 8.19.4 - /usr/bin/npm
```

### package.json dependencies

```json
{
  "dependencies": {
    "@fullcalendar/bootstrap5": "6.1.11",
    "@fullcalendar/core": "6.1.11",
    "@fullcalendar/daygrid": "6.1.11",
    "@fullcalendar/icalendar": "6.1.11",
    "@fullcalendar/interaction": "6.1.11",
    "@fullcalendar/list": "6.1.11",
    "@fullcalendar/luxon3": "6.1.11",
    "@fullcalendar/timegrid": "6.1.11",
    "@fullcalendar/vue3": "6.1.11",
    "@popperjs/core": "2.11.8",
    "@twuni/emojify": "1.0.2",
    "bootstrap": "5.3.3",
    "bootstrap-icons": "1.11.3",
    "browser-fs-access": "0.35.0",
    "caniuse-lite": "1.0.30001603",
    "d3": "7.9.0",
    "file-saver": "2.0.5",
    "highcharts": "11.4.0",
    "ical.js": "1.5.0",
    "jquery": "3.7.1",
    "js-cookie": "3.0.5",
    "list.js": "2.3.1",
    "lodash": "4.17.21",
    "lodash-es": "4.17.21",
    "luxon": "3.4.4",
    "moment": "2.30.1",
    "moment-timezone": "0.5.45",
    "ms": "2.1.3",
    "murmurhash-js": "1.0.0",
    "naive-ui": "2.38.1",
    "pinia": "2.1.7",
    "pinia-plugin-persist": "1.0.0",
    "select2": "4.1.0-rc.0",
    "select2-bootstrap-5-theme": "1.3.0",
    "send": "0.18.0",
    "shepherd.js": "11.2.0",
    "slugify": "1.6.6",
    "sortablejs": "1.15.2",
    "vanillajs-datepicker": "1.3.4",
    "vue": "3.4.21",
    "vue-router": "4.3.0",
    "zxcvbn": "4.4.2"
  },
  "devDependencies": {
    "@parcel/optimizer-data-url": "2.12.0",
    "@parcel/transformer-inline-string": "2.12.0",
    "@parcel/transformer-sass": "2.12.0",
    "@rollup/pluginutils": "5.1.0",
    "@vitejs/plugin-vue": "4.6.2",
    "@vue/language-plugin-pug": "2.0.7",
    "browserlist": "latest",
    "c8": "9.1.0",
    "eslint": "8.57.0",
    "eslint-config-standard": "17.1.0",
    "eslint-plugin-cypress": "2.15.1",
    "eslint-plugin-import": "2.29.1",
    "eslint-plugin-n": "16.6.2",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "6.1.1",
    "eslint-plugin-vue": "9.24.0",
    "html-validate": "8.18.1",
    "jquery-migrate": "3.4.1",
    "parcel": "2.12.0",
    "pug": "3.0.2",
    "sass": "1.72.0",
    "seedrandom": "3.0.5",
    "vite": "4.5.3"
  }
}
```

### Steps to reproduce

Open vscode project in devcontainers with the `vue.volar` extension defined into the `devcontainer.json` config. After a few seconds, vscode crashes with error "Cannot reconnect. Please reload the window.".

Pinning `vue.volar` to the older `2.2.10` resolves the issue.

### What is expected?

No crash.

### What is actually happening?

After a few seconds after running inside the container (as Volar gets loaded), vscode crashes with error "Cannot reconnect. Please reload the window.". Reloading the vscode window works but you now lost any previous context. The bug was reproducible by 2 other users on macOS and Windows.

![Image](https://github.com/user-attachments/assets/43d3098c-811c-4d30-a899-095d95f893dc)

### Link to minimal reproduction

https://github.com/ietf-tools/datatracker/tree/06a4182e0287769673106d5d0c415f0ec92cdb46

**Comment by KazariEX** [comment]
I noticed that you are using pug. We have fixed a bug in v3.0.1 that would cause an infinite loop in pug. Please try using v3.0.1.

**Comment by NGPixel** [comment]
@KazariEX I'm already using 3.0.1 and the crash is still happening.

**Comment by KazariEX** [comment]
Are there any error messages in Output - Vue Language Server?

**Comment by NGPixel** [comment]
The "Vue Langage Server" is not listed in the available outputs up to the crash (even after clicking Cancel on the error). After reloading the window, it only gets listed after opening a .vue file and its output only contains:
```
[Vue] Load plugin failed: @vue/language-plugin-pug
```

Updating `@vue/language-plugin-pug` to the latest `3.0.1` doesn't fix the problem either.

**Comment by KazariEX** [comment]
Can you try using other plugins and see if the same thing happens? For example https://vue-macros.dev/guide/bundler-integration.html#volar-support. You don't need to actually use their functionality, just see if other plugins also fail to load.

**Comment by NGPixel** [comment]
It seems to be the case:
```
[Vue] Load plugin failed: vue-macros/volar
[Vue] Load plugin failed: @vue/language-plugin-pug
```

**Comment by Lupennat** [comment]
I have the same problem, which can easily be replicated just by using the devcontainer file without any package.json or node_modules.
```ts
{
	"name": "Node.js & TypeScript",
	"image": "mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm",

	"customizations": {
		"vscode": {
			"extensions": [
				"Vue.volar"
			]
		}
	}
}
```
After the first build, the container hangs and must be reloaded.
If I remove the extension or force version 2.2.10 and do a new build, the container does not crash.

Vscode version: 1.101.2 (Universal)
Commit: 2901c5ac6db8a986a5666c3af51ff804d05af0d4
Date: 2025-06-24T20:27:15.391Z (1 wk ago)
Electron: 35.5.1
ElectronBuildId: 11727614
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Darwin arm64 24.5.0

extensions installed: ["ms-vscode-remote.remote-containers@0.417.0"]

**Comment by arabcoders** [comment]
I'm experiencing the same issue, but with a slightly different scenario. VS Code rarely crashes when working on an actual Vue project. However, the crash consistently occurs when I open a **Python project that doesn't contain a `package.json` file** — this seems to be the common trigger.

A few additional observations:

* This issue does **not** occur when using an Ubuntu client — it only happens on **Windows 11** in my case.
* The remote target is a Debian server with the following specs:

  ```
  Linux 6.1.0-37-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.140-1 (2025-05-22) x86_64 GNU/Linux
  CPU: i9-14900K
  RAM: 128GB
  Node.js: v20.19.3
  pnpm: v10.11.0
  yarn: v1.22.22
  npm: v10.8.2
  ```

**VS Code Info (Windows client):**

```
Version: 1.102.0 (user setup)
Commit: cb0c47c0cfaad0757385834bd89d410c78a856c0
Date: 2025-07-09T22:10:34.600Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Windows_NT x64 10.0.26100
```

I did the usual remove .vscode-server folder reinstalled etc, and the issue still persist.

Let me know if there’s anything I can provide (logs, traces, etc.) to help debug this further.

**Comment by DL6ER** [comment]
I can confirm the same issue **without a devcontainer** scenario. `v3.0.1` simply crashed on opening any `vue` file. After manually downgrading to v2.2.10, and then updating back to v3.0.1, there is no crash any longer

<img width="290" height="565" alt="Image" src="https://github.com/user-attachments/assets/2eda5049-64b3-4300-a34b-9edc3d47b967" />

<img width="613" height="499" alt="Image" src="https://github.com/user-attachments/assets/69678c34-08ec-498d-bec7-5460d7527bc2" />

<img width="614" height="95" alt="Image" src="https://github.com/user-attachments/assets/7cc3ab18-6bd5-4478-9012-f1889e6e6d15" />

Unfortunately, this means I am not of much help with debugging the current issue but it figured I'd mention it as it may work as temporary workaround also for others.

**Comment by KazariEX** [comment]
@DL6ER Could you provide a minimal reproduction?

**Comment by DL6ER** [comment]
No, unfortunately not. As I said, since downgrading to v2 and then re-upgrading to v3, I don't have this issue any longer...

**Comment by cxammar** [comment]
Same issue here

**Comment by Jonathan-Harty** [comment]
As an extension of the devcontainers, this is also an issue in WSL.

**Comment by GalenReich** [comment]
I have the same issue when using WSL, rolling back to v2 solves it in the same way.

My debug logs are similarly unhelpful.

To reproduce (with 3.0.0 and 3.0.1), I use an empty directory with some minimal typescript file, located on the WSL file system.

The file should be opened in the editor.

<details>
  <summary>System version info</summary>
  VS Code version: Code 1.102.0 (cb0c47c0cfaad0757385834bd89d410c78a856c0, 2025-07-09T22:10:34.600Z)
  OS version: Windows_NT x64 10.0.26100
  WSL version: Linux x64 6.6.87.2-microsoft-standard-WSL2
</details>

<details>
  <summary>Boilerplate example.tsx</summary>

  ```js
  import React from 'react';
  
  type ExampleProps = {
      title: string;
      count: number;
      isActive?: boolean;
  };
  
  const ExampleComponent: React.FC<ExampleProps> = ({ title, count, isActive = false }) => (
      <div>
          <h1>{title}</h1>
          <p>Count: {count}</p>
          <p>Status: {isActive ? 'Active' : 'Inactive'}</p>
      </div>
  );
  
  export default ExampleComponent;
  ```

</details>


Relatedly, there is a small discussion here: https://github.com/microsoft/vscode-remote-release/issues/11091

And it seems that other extensions might be hitting a similar bug: https://github.com/continuedev/continue/issues/6612

**Comment by arabcoders** [comment]
using v3.0.1i am experiencing the same issue as windows client not as frequent

```
Version: 1.102.0
Commit: cb0c47c0cfaad0757385834bd89d410c78a856c0
Date: 2025-07-09T22:10:34.600Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Linux x64 6.11.0-29-generic
```

**Comment by Druelik** [comment]
Same problem crashing with 3.0.x, fixed by downgrading to 2.2.10. Running vscode under WSL. Vscode version -> 1.102.1. For me the problem started after updating vscode to the latest version.
```
  System:
    OS: Linux 6.6 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 24.73 GB / 31.30 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.14.0 - /run/user/1000/fnm_multishells/34253_1752766638367/bin/node
    npm: 10.9.2 - /run/user/1000/fnm_multishells/34253_1752766638367/bin/npm
    pnpm: 10.12.4 - ~/.local/share/pnpm/pnpm
```

**Comment by robokozo** [comment]
I have a similar crash but from when connecting via remote SSH. It has been an odd and inconsistent experience for me. 

Things I've noticed:
- When it crashes, the "Extensions" pane for the SSH: does not render (the section appears empty)
- If I happen to click on the "Extensions" pane before the connection to the SSH server completes, it doesn't seem to crash.
- If a project has a package.json, simply reloading vs code will fix it without doing the "click extensions" workaround from above.
 - If a project does not have a package.json, reloading vscode crashes in the same way unless I do the "click extensions" workaround

@KazariEX should I report this issue separately since it's not directly related to devcontainers?

But to everyone else, if you can provide additional information. If you weren't aware VSCode is just an Electron instance (Chrome) and you can see the Dev Tools. We might get better info if you can provide the console errors that are occurring.

Here are some of mine
## No Crash Console Output
```
INFO Invoking resolveAuthority(ssh-remote)...
log.ts:440  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
log.ts:440  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
log.ts:440  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][257ms] returned Managed(1)
log.ts:440  INFO resolveAuthority(ssh-remote) returned 'Managed(1)' after 258 ms
log.ts:440  INFO Creating a socket (renderer-Management-1554d5e6-7130-4279-847d-0b81f6387906)...
log.ts:440  INFO Creating a socket (renderer-ExtensionHost-c8e07a63-151e-4efb-aba6-b231db9c0a8f)...
log.ts:440  INFO Creating a socket (renderer-ExtensionHost-c8e07a63-151e-4efb-aba6-b231db9c0a8f) was successful after 70 ms.
log.ts:440  INFO Creating a socket (renderer-Management-1554d5e6-7130-4279-847d-0b81f6387906) was successful after 71 ms.
log.ts:440  INFO Settings Sync: Account status changed from uninitialized to available
log.ts:440  INFO [perf] Render performance baseline is 9ms
```
## Crashing Console Output
```
INFO Invoking resolveAuthority(ssh-remote)...
log.ts:440  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
log.ts:440  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
log.ts:440  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][240ms] returned Managed(1)
log.ts:440  INFO resolveAuthority(ssh-remote) returned 'Managed(1)' after 240 ms
log.ts:440  INFO Creating a socket (renderer-Management-9719150d-20f8-489d-af33-21acf808c840)...
log.ts:440  INFO Creating a socket (renderer-ExtensionHost-583d3528-0d33-4b0b-a756-c278a2dd216e)...
log.ts:440  INFO Creating a socket (renderer-Management-9719150d-20f8-489d-af33-21acf808c840) was successful after 100 ms.
log.ts:440  INFO Creating a socket (renderer-ExtensionHost-583d3528-0d33-4b0b-a756-c278a2dd216e) was successful after 134 ms.
log.ts:440  INFO Settings Sync: Account status changed from uninitialized to available
log.ts:440  INFO Creating a socket (renderer-ExtensionHost-7fca3e4a-5cc9-4e7d-92f7-cd03b17cd0fd)...
log.ts:440  INFO Creating a socket (renderer-ExtensionHost-7fca3e4a-5cc9-4e7d-92f7-cd03b17cd0fd) returned an error after 0 ms.
log.ts:460   ERR Canceled: Canceled
    at new Han (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3397:35744)
    at Vkt.U (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3397:40391)
    at n.<computed>.r.charCodeAt.n.<computed> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3397:37880)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:547:1762
    at new Promise (<anonymous>)
    at Object.connect (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:547:1672)
    at bms.connect (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:547:1416)
    at den (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2733:29584)
    at fen (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2733:30325)
    at Xxi (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2733:32239)
log.ts:460   ERR [remote-connection][ExtensionHost][7fca3…][initial][Managed(1)] socketFactory.connect() failed or timed out. Error:

```
And it repeats

## EDIT: I got into a state where enabling the Vue (Official) extension on the SSH environment crashes VSCode. 
```
INFO Creating a socket (renderer-ExtensionHost-01e0c460-c19d-43ed-96c3-50a6852032be)...
log.ts:440  INFO Creating a socket (renderer-ExtensionHost-01e0c460-c19d-43ed-96c3-50a6852032be) returned an error after 1 ms.
log.ts:460   ERR Canceled: Canceled
    at new Han (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3397:35744)
    at Vkt.U (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3397:40391)
    at n.<computed>.r.charCodeAt.n.<computed> (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3397:37880)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:547:1762
    at new Promise (<anonymous>)
    at Object.connect (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:547:1672)
    at bms.connect (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:547:1416)
    at den (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2733:29584)
    at fen (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2733:30325)
    at Xxi (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2733:32239)
log.ts:460   ERR [remote-connection][ExtensionHost][01e0c…][initial][Managed(1)] socketFactory.connect() failed or timed out. Error:
```
And it repeats. When I reload, the Vue extension is enabled and it doesn't crash

**Comment by johnsoncodehk** [comment]
I am unable to test WSL, can anyone assist us in investigating remotely?

https://github.com/vuejs/language-tools/wiki/Help-Us-Investigate-Issues-Remotely

**Comment by johnsoncodehk** [comment]
We found that this is caused by executing the "Developer: Restart Extension Host" command inside the Vue extension, and it can be reproduced by the user manually executing the "Developer: Restart Extension Host" command.

https://github.com/vuejs/language-tools/blob/945a6cd90266499d924f81cfa8826299a4ff7905/extensions/vscode/index.ts#L222

**Comment by so1ve** [comment]
This issue is not related to language-tools, please track https://github.com/microsoft/vscode-remote-release/issues/11091.

**Comment by robokozo** [comment]
@so1ve It's good to know! But also curious because I did testing to isolate the problematic extension. I only experienced problems when the vue extension was enabled. For my own knowledge and benefit, do you know why it would only impact this extension if there is a broader issue at play?

**Comment by paulcwatts** [comment]
This is a minimal reproduction on macOS, no WSL required: https://github.com/paulcwatts/vscode-bug-test

Basically the repo is just the output of `pnpm create vue@latest` with the addition of a minimal devcontainer.json file.

* Extension version: 3.0.2
* VSCode version
```
Version: 1.102.1 (Universal)
Commit: 7adae6a56e34cb64d08899664b814cf620465925
Date: 2025-07-15T16:41:17.147Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Darwin arm64 24.5.0
```
* Vue version: 3.5.17
* Typescript version: None
* System info (within the devcontainer):
```

  System:
    OS: Linux 6.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (10) arm64 unknown
    Memory: 22.13 GB / 23.43 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 22.14.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.9.2 - /usr/local/bin/npm
    pnpm: 10.6.4 - /usr/local/share/npm-global/bin/pnpm
```
Host info:
```
  System:
    OS: macOS 15.5
    CPU: (14) arm64 Apple M4 Pro
    Memory: 11.79 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - ~/Library/pnpm/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.2 - ~/Library/pnpm/npm
    pnpm: 10.6.5 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 138.1.80.120
    Chrome: 138.0.7204.158
    Safari: 18.5
```

* package.json: https://github.com/paulcwatts/vscode-bug-test/blob/main/package.json

## Steps to reproduce:

1. Clone this project: https://github.com/paulcwatts/vscode-bug-test
2. Open it in a devcontainer
3. Open App.vue

You get the "Cannot reconnect. Please reload the window." error

**Comment by so1ve** [comment]
> [@so1ve](https://github.com/so1ve) It's good to know! But also curious because I did testing to isolate the problematic extension. I only experienced problems when the vue extension was enabled. For my own knowledge and benefit, do you know why it would only impact this extension if there is a broader issue at play?

Does Remote crash when you call `Restart Extension Host` with Vue (Official) disabled? On my laptop it constantly crashes

Vue calls `Restart` internally, see https://github.com/vuejs/language-tools/issues/5478#issuecomment-3089551022

**Comment by so1ve** [comment]
@paulcwatts Please check https://github.com/microsoft/vscode-remote-release/issues/11091. `vscode-remote-release` affects both WSL and Devcontainer
